compute_components_flag: false
config_ar: !!python/object:neuralprophet.configure.AR
  ar_reg: null
  n_lags: 0
  reg_lambda: null
config_events: null
config_holidays: !!python/object:neuralprophet.configure.Holidays
  country: PT
  holiday_names: !!set
    Ano Novo: null
    "Assun\xE7\xE3o de Nossa Senhora": null
    Corpo de Deus: null
    Dia da Liberdade: null
    Dia de Natal: null
    Dia de Portugal: null
    Dia de Todos os Santos: null
    Dia do Trabalhador: null
    "Imaculada Concei\xE7\xE3o": null
    "Implanta\xE7\xE3o da Rep\xFAblica": null
    "P\xE1scoa": null
    "Restaura\xE7\xE3o da Independ\xEAncia": null
    Sexta-feira Santa: null
  lower_window: 0
  mode: additive
  reg_lambda: null
  upper_window: 0
config_lagged_regressors: null
config_normalization: !!python/object:neuralprophet.configure.Normalization
  global_data_params: !!python/object/apply:collections.OrderedDict
  - - - ds
      - &id001 !!python/object:neuralprophet.df_utils.ShiftScale
        scale: !!python/object/apply:pandas._libs.tslibs.timedeltas._timedelta_unpickle
        - 75600000000000000
        - 10
        shift: !!python/object/apply:pandas._libs.tslibs.timestamps._unpickle_timestamp
        - 1325376000000000000
        - null
        - null
        - 10
    - - y
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: 1.0
        shift: 0.0
  global_normalization: true
  global_time_normalization: true
  local_data_params: !!python/object/apply:collections.OrderedDict
  - - - __df__
      - !!python/object/apply:collections.OrderedDict
        - - - ds
            - *id001
          - - y
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
  normalize: true
  unknown_data_normalization: false
config_regressors: null
config_seasonality: !!python/object:neuralprophet.configure.ConfigSeasonality
  computation: fourier
  condition_name: null
  daily_arg: true
  global_local: global
  mode: multiplicative
  periods: !!python/object/apply:collections.OrderedDict
  - - - yearly
      - !!python/object:neuralprophet.configure.Season
        arg: true
        condition_name: null
        period: 365.25
        resolution: 6
    - - weekly
      - !!python/object:neuralprophet.configure.Season
        arg: true
        condition_name: null
        period: 7
        resolution: 3
    - - daily
      - !!python/object:neuralprophet.configure.Season
        arg: true
        condition_name: null
        period: 1
        resolution: 6
  reg_lambda: 0
  weekly_arg: true
  yearly_arg: true
config_train: !!python/object:neuralprophet.configure.Train
  batch_size: 64
  epochs: 300
  lambda_delay: 150
  learning_rate: 0.8
  loss_func: !!python/object:torch.nn.modules.loss.MSELoss
    _backward_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _buffers: !!python/object/apply:collections.OrderedDict
    - []
    _forward_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _is_full_backward_hook: null
    _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _modules: !!python/object/apply:collections.OrderedDict
    - []
    _non_persistent_buffers_set: !!set {}
    _parameters: !!python/object/apply:collections.OrderedDict
    - []
    _state_dict_hooks: !!python/object/apply:collections.OrderedDict
    - []
    reduction: none
    training: true
  loss_func_name: MSELoss
  lr_finder_args: {}
  n_data: 876
  newer_samples_start: 0.0
  newer_samples_weight: 2
  optimizer: !!python/name:torch.optim.adamw.AdamW ''
  optimizer_args:
    weight_decay: 0.001
  quantiles:
  - 0.5
  reg_delay_pct: 0.5
  reg_lambda_trend: null
  scheduler: !!python/name:torch.optim.lr_scheduler.OneCycleLR ''
  scheduler_args:
    anneal_strategy: cos
    div_factor: 100.0
    final_div_factor: 5000.0
    pct_start: 0.3
  trend_reg_threshold: false
config_trend: !!python/object:neuralprophet.configure.Trend
  changepoints: null
  changepoints_range: 0.5
  growth: linear
  n_changepoints: 15
  trend_global_local: global
  trend_reg: 0
  trend_reg_threshold: null
d_hidden: 256
id_list:
- __df__
max_lags: 0
meta_used_in_model: false
metrics:
  MAE: !!python/object:torchmetrics.regression.mae.MeanAbsoluteError
    _backward_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _buffers: !!python/object/apply:collections.OrderedDict
    - []
    _cache: null
    _computed: null
    _defaults:
      sum_abs_error: !!python/object/apply:torch._utils._rebuild_tensor_v2
      - !!python/object/apply:torch.storage._load_from_bytes
        - !!binary |
          gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
          AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
          aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
          Z2UKcQFYCwAAADEwODc5NTM3MjE2cQJYAwAAAGNwdXEDSwFOdHEEUS6AAl1xAFgLAAAAMTA4Nzk1
          MzcyMTZxAWEuAQAAAAAAAAAAAAAA
      - 0
      - !!python/tuple []
      - !!python/tuple []
      - false
      - !!python/object/apply:collections.OrderedDict
        - []
      total: !!python/object/apply:torch._utils._rebuild_tensor_v2
      - !!python/object/apply:torch.storage._load_from_bytes
        - !!binary |
          gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
          AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
          aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApMb25nU3RvcmFn
          ZQpxAVgLAAAAMTA4Nzk1NTIzODRxAlgDAAAAY3B1cQNLAU50cQRRLoACXXEAWAsAAAAxMDg3OTU1
          MjM4NHEBYS4BAAAAAAAAAAAAAAAAAAAA
      - 0
      - !!python/tuple []
      - !!python/tuple []
      - false
      - !!python/object/apply:collections.OrderedDict
        - []
    _device: !!python/object/apply:torch.device
    - cpu
    _enable_grad: false
    _forward_cache: null
    _forward_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _is_full_backward_hook: null
    _is_synced: false
    _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _modules: !!python/object/apply:collections.OrderedDict
    - []
    _non_persistent_buffers_set: !!set {}
    _parameters: !!python/object/apply:collections.OrderedDict
    - []
    _persistent:
      sum_abs_error: false
      total: false
    _reductions:
      sum_abs_error: &id002 !!python/name:torchmetrics.utilities.data.dim_zero_sum ''
      total: *id002
    _should_unsync: true
    _state_dict_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _to_sync: true
    _update_count: 0
    compute_on_cpu: false
    dist_sync_fn: null
    dist_sync_on_step: false
    process_group: null
    sum_abs_error: !!python/object/apply:torch._utils._rebuild_tensor_v2
    - !!python/object/apply:torch.storage._load_from_bytes
      - !!binary |
        gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
        AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
        aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
        Z2UKcQFYCwAAADExNjAxNzg1OTg0cQJYAwAAAGNwdXEDSwFOdHEEUS6AAl1xAFgLAAAAMTE2MDE3
        ODU5ODRxAWEuAQAAAAAAAAAAAAAA
    - 0
    - !!python/tuple []
    - !!python/tuple []
    - false
    - !!python/object/apply:collections.OrderedDict
      - []
    sync_on_compute: true
    total: !!python/object/apply:torch._utils._rebuild_tensor_v2
    - !!python/object/apply:torch.storage._load_from_bytes
      - !!binary |
        gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
        AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
        aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApMb25nU3RvcmFn
        ZQpxAVgLAAAAMTE2MDIwNDE0ODhxAlgDAAAAY3B1cQNLAU50cQRRLoACXXEAWAsAAAAxMTYwMjA0
        MTQ4OHEBYS4BAAAAAAAAAAAAAAAAAAAA
    - 0
    - !!python/tuple []
    - !!python/tuple []
    - false
    - !!python/object/apply:collections.OrderedDict
      - []
    training: true
  RMSE: !!python/object:torchmetrics.regression.mse.MeanSquaredError
    _backward_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _buffers: !!python/object/apply:collections.OrderedDict
    - []
    _cache: null
    _computed: null
    _defaults:
      sum_squared_error: !!python/object/apply:torch._utils._rebuild_tensor_v2
      - !!python/object/apply:torch.storage._load_from_bytes
        - !!binary |
          gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
          AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
          aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
          Z2UKcQFYCwAAADExNjAxNzk0NzY4cQJYAwAAAGNwdXEDSwFOdHEEUS6AAl1xAFgLAAAAMTE2MDE3
          OTQ3NjhxAWEuAQAAAAAAAAAAAAAA
      - 0
      - !!python/tuple []
      - !!python/tuple []
      - false
      - !!python/object/apply:collections.OrderedDict
        - []
      total: !!python/object/apply:torch._utils._rebuild_tensor_v2
      - !!python/object/apply:torch.storage._load_from_bytes
        - !!binary |
          gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
          AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
          aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApMb25nU3RvcmFn
          ZQpxAVgLAAAAMTA4Nzk1OTMxMjBxAlgDAAAAY3B1cQNLAU50cQRRLoACXXEAWAsAAAAxMDg3OTU5
          MzEyMHEBYS4BAAAAAAAAAAAAAAAAAAAA
      - 0
      - !!python/tuple []
      - !!python/tuple []
      - false
      - !!python/object/apply:collections.OrderedDict
        - []
    _device: !!python/object/apply:torch.device
    - cpu
    _enable_grad: false
    _forward_cache: null
    _forward_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _is_full_backward_hook: null
    _is_synced: false
    _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _modules: !!python/object/apply:collections.OrderedDict
    - []
    _non_persistent_buffers_set: !!set {}
    _parameters: !!python/object/apply:collections.OrderedDict
    - []
    _persistent:
      sum_squared_error: false
      total: false
    _reductions:
      sum_squared_error: *id002
      total: *id002
    _should_unsync: true
    _state_dict_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _to_sync: true
    _update_count: 0
    compute_on_cpu: false
    dist_sync_fn: null
    dist_sync_on_step: false
    process_group: null
    squared: false
    sum_squared_error: !!python/object/apply:torch._utils._rebuild_tensor_v2
    - !!python/object/apply:torch.storage._load_from_bytes
      - !!binary |
        gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
        AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
        aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
        Z2UKcQFYCwAAADExNjAyMTA0MTI4cQJYAwAAAGNwdXEDSwFOdHEEUS6AAl1xAFgLAAAAMTE2MDIx
        MDQxMjhxAWEuAQAAAAAAAAAAAAAA
    - 0
    - !!python/tuple []
    - !!python/tuple []
    - false
    - !!python/object/apply:collections.OrderedDict
      - []
    sync_on_compute: true
    total: !!python/object/apply:torch._utils._rebuild_tensor_v2
    - !!python/object/apply:torch.storage._load_from_bytes
      - !!binary |
        gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
        AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
        aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApMb25nU3RvcmFn
        ZQpxAVgLAAAAMTE2MDIxMDk1MDRxAlgDAAAAY3B1cQNLAU50cQRRLoACXXEAWAsAAAAxMTYwMjEw
        OTUwNHEBYS4BAAAAAAAAAAAAAAAAAAAA
    - 0
    - !!python/tuple []
    - !!python/tuple []
    - false
    - !!python/object/apply:collections.OrderedDict
      - []
    training: true
n_forecasts: 1
n_lags: 0
num_hidden_layers: 25
num_seasonalities_modelled: 1
num_trends_modelled: 1
